### ISSUE TITLE
Update to fletcher:0.5.2

### ISSUE THREAD

**Issue by Akilon27** [Le-foucheur/Typst-VarTable#7]
I tried to see what needed to be changed and this is what I found (usinf the tabvar.typ present in the repo) :

-0.73 at the beginning of line 137 instead of -0.86 and label-sep: -5.1pt lines 208 and 229.

The only other issue is if there is "||" at the beginning of a variation line but I didn't find how to solve it (cf ex. part 2.2.2.3 and 3.1)

**Comment by Le-foucheur** [comment]
it might be a good idea to update my package, according to fletcher
and thank you for making my work easier, even if the value of -0.74 was better (because otherwise it left a small space between the two lines) 
and above all gg for having the courage to reread and understand the mess that is my package!
But normally I've sorted everything out and it should be updated in no time. 
and thank you
